baseURL = 'https://scottnbarnett.com/'
languageCode = 'en-us'
title = 'Scott Barnett'
theme = "hugo-initio"

[params]
    name = "Scott Barnett"
    description = "Technologist, Researcher and Engineer"
    email = "scott.barnett@deakin.com"
    # phone = "+234 23 9873237"
    # address = "234 Hidden Pond Road, Ashland City, TN 37015"
    year = 2021
    avatar = "images/scott.jpeg"
    avatarclass = "circle"
    background = ""
    banner = "images/washed-ai.png"
    favicon = "images/favicon-scott.jpeg"
    DateForm = "January 2, 2006"
    author = "Sergey Pozhilov (GetTemplate.com)"

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownloads = true
    showClients = true

    showFooterContact = true
    showFooterFollowMe = true
    showFooterTextWidget = false
    showFooterFormWidget = false

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  
# [params.disqus]
#     site = "hugo-initio-site.disqus.com"

# [params.sharethis]
#     property = "123456789012345678901234"
#     custom = true

[params.google.analytics]
    trackerID = "G-FZ67J77C3E"

[[params.social]]
	title = "twitter"
	url = "https://twitter.com/scottynb"
    icon = "fab fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "linkedin"
	url = "https://au.linkedin.com/in/scott-barnett-9b94b768"
    icon = "fab fa-linkedin"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "github"
	url = "https://github.com/nickname"
    icon = "fab fa-github"
    footer = false
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:scott.barnett@deakin.com"
    icon = "fas fa-envelope-square"
    footer = true
    sharethis = true
    network = "email"
[[params.social]]
	title = "scholar"
	url = "https://scholar.google.com.au/citations?user=PJcpaRAAAAAJ&hl=en&oi=ao"
    icon = "fab fa-google"
    footer = true
    sharethis = false
    network = ""
